-- Тексты страницы «Kontakty» (Pages.id = 10) для редактирования в ImagoAdmin.
-- Перенесены из прежней статичной разметки Views/Home/Kontakty.cshtml. Скрипт можно запускать повторно:
-- добавляет только отсутствующие тексты, существующие (уже отредактированные) не трогает.
-- Блоки: Kontakty_Person{N}_* — контактные лица, Kontakty_Partner{N}_* — spolupracovníci. Блок удаляется/добавляется в ImagoAdmin (вкладка «Bloky»).

DECLARE @texts TABLE (EntryKey NVARCHAR(200) NOT NULL, ContentText NVARCHAR(MAX) NOT NULL);
INSERT INTO @texts (EntryKey, ContentText) VALUES
    (N'Kontakty_Title', N'Kontakty'),
    (N'Kontakty_Intro1', N'Líbí se Vám naše výrobky, chcete se nás na něco zeptat či nám něco sdělit?'),
    (N'Kontakty_Intro2', N'<strong>Napište nám.</strong> Všechny činnosti provádí naši proškolení <strong>profesionálové</strong>. Pracujeme <strong>rychle, přesně a bez zbytečných nákladů</strong> na Vaší straně.'),
    (N'Kontakty_Intro3', N'S důvěrou se na nás obraťte. Ochotně odpovíme na Vaše dotazy a připravíme cenovou nabídku k vybranému produktu. Neváhejte a volejte, pište na e-mail nebo použijte kontaktní formulář níže.'),
    (N'Kontakty_Firm_Name', N'IMAGO D&T, s.r.o.'),
    (N'Kontakty_Firm_Person', N'Jaroslava Medvecová'),
    (N'Kontakty_Firm_Street', N'Mandysova 1410/26'),
    (N'Kontakty_Firm_City', N'500 12 Hradec Králové 12'),
    (N'Kontakty_Firm_Phone', N'+420 602 411 872'),
    (N'Kontakty_Firm_Mobile', N'+420 777 182 900'),
    (N'Kontakty_Firm_Email', N'imagodt@imagodt.cz'),
    (N'Kontakty_Firm_ICO', N'26000245'),
    (N'Kontakty_Firm_DIC', N'CZ26000245'),
    (N'Kontakty_Firm_Court', N'Společnost je vedená u Krajského soudu v Hradci Králové, spisová značka C 19251'),
    (N'Kontakty_Prov_Title', N'Provozovna'),
    (N'Kontakty_Prov_Name', N'Biorezonanční centrum - Diacom'),
    (N'Kontakty_Prov_Person', N'Vladimír Burčík - odpovědný vedoucí, hlavní školitel a specialista'),
    (N'Kontakty_Prov_Street', N'Gebauerova 1024/2'),
    (N'Kontakty_Prov_City', N'500 02 Hradec Králové 2'),
    (N'Kontakty_Prov_Mobile', N'+420 603 554 483'),
    (N'Kontakty_Prov_Email', N'vladimirburcik@imagodt.cz'),
    (N'Kontakty_Map_Title', N'Mapa provozovny'),
    (N'Kontakty_Persons_Title', N'Kontaktní osoby'),
    (N'Kontakty_Person1_Name', N'Jaroslava Medvecová'),
    (N'Kontakty_Person1_Role', N'Jednatelka'),
    (N'Kontakty_Person1_Mobile', N'+420 777 182 900'),
    (N'Kontakty_Person1_Email', N'imagodt@imagodt.cz'),
    (N'Kontakty_Person2_Name', N'Ing. Dušan Medvec'),
    (N'Kontakty_Person2_Role', N'Jednatel, marketing a prodej'),
    (N'Kontakty_Person2_Mobile', N'+420 602 411 872'),
    (N'Kontakty_Person2_Email', N'd.medvec@tiscali.cz'),
    (N'Kontakty_Person3_Name', N'Jana Macková'),
    (N'Kontakty_Person3_Role', N'Specialista prodeje'),
    (N'Kontakty_Person3_Mobile', N'+420 777 900 412'),
    (N'Kontakty_Person3_Email', N'jana.medvecova@centrum.cz'),
    (N'Kontakty_Partners_Title', N'Spolupracujeme'),
    (N'Kontakty_Partner1_Region', N'Spolupráce v Čechách'),
    (N'Kontakty_Partner1_Type', N'Spolupracovník IMAGO D&T,s.r.o.'),
    (N'Kontakty_Partner1_Name', N'Vladimír Burčík - hlavní školitel'),
    (N'Kontakty_Partner1_Address', N'P.O.BOX č.20, 500 12 Hradec Králové'),
    (N'Kontakty_Partner1_Country', N'Česká republika'),
    (N'Kontakty_Partner1_Phone', N'+420 603 554 483'),
    (N'Kontakty_Partner1_Email', N'burcik@centrum.cz'),
    (N'Kontakty_Partner1_ICO', N'13207440'),
    (N'Kontakty_Partner1_MapUrl', N'https://maps.google.com/maps?q=Hradec+Kr%C3%A1lov%C3%A9,+%C4%8Cesk%C3%A1+republika&hl=cs&ie=UTF8&sll=49.797096,18.371494&sspn=0.083105,0.181789&oq=hradec+&hnear=Hradec+Kr%C3%A1lov%C3%A9,+%C4%8Cesk%C3%A1+republika&t=m&z=12'),
    (N'Kontakty_Partner2_Region', N'Spolupráce v Čechách'),
    (N'Kontakty_Partner2_Type', N'Obchodně školící servisní centrum'),
    (N'Kontakty_Partner2_Name', N'MUDr. Jan Štěpán'),
    (N'Kontakty_Partner2_Address', N'Jiráskova 1320, 29301 Mladá Boleslav'),
    (N'Kontakty_Partner2_Country', N'Česká republika'),
    (N'Kontakty_Partner2_Phone', N'+421 903 653 002'),
    (N'Kontakty_Partner2_Email', N'janxstepan@gmail.com'),
    (N'Kontakty_Partner2_ICO', N'73616737'),
    (N'Kontakty_Partner2_MapUrl', N'https://maps.google.com/maps?q=Jir%C3%A1skova+1320,+Mlad%C3%A1+Boleslav,+29301&hl=cs&ie=UTF8&sll=48.144265,17.096143&sspn=0.010738,0.022724&hnear=Jir%C3%A1skova+1320,+293+01+Mlad%C3%A1+Boleslav,+%C4%8Cesk%C3%A1+republika&t=m&z=16'),
    (N'Kontakty_Partner3_Region', N'Spolupráce v Čechách'),
    (N'Kontakty_Partner3_Type', N'Obchodně školící servisní centrum'),
    (N'Kontakty_Partner3_Name', N'Miriam a Peter Bobošíkovi'),
    (N'Kontakty_Partner3_Address', N'U Statku 301/1, 736 01 Havířov'),
    (N'Kontakty_Partner3_Country', N'Česká republika'),
    (N'Kontakty_Partner3_Phone', N'+420 774 878 148'),
    (N'Kontakty_Partner3_Email', N'petobobo@seznam.cz'),
    (N'Kontakty_Partner3_ICO', N'09 54 558'),
    (N'Kontakty_Partner3_MapUrl', N'https://maps.google.com/maps?q=U+Statku+301%2F1+Hav%C3%AD%C5%99ov+-+Bludovice+736+01&hl=cs&ie=UTF8&sll=50.077136,14.503183&sspn=0.010328,0.022724&hnear=U+Statku+301%2F1,+736+01+Hav%C3%AD%C5%99ov,+%C4%8Cesk%C3%A1+republika&t=m&z=16'),
    (N'Kontakty_Partner4_Region', N'Spolupráce na Slovensku'),
    (N'Kontakty_Partner4_Type', N'Obchodně školící servisní centrum'),
    (N'Kontakty_Partner4_Name', N'Dr.Am Mirka Fedorčáková'),
    (N'Kontakty_Partner4_Address', N'Hlavná 33, 080 01 Prešov'),
    (N'Kontakty_Partner4_Country', N'Slovensko'),
    (N'Kontakty_Partner4_Phone', N'+421 905 980 486'),
    (N'Kontakty_Partner4_Email', N'drcaura@gmail.com'),
    (N'Kontakty_Partner4_ICO', N'44227701'),
    (N'Kontakty_Partner4_MapUrl', N'https://maps.google.com/maps?q=Hlavn%C3%A1+33+080+01+Pre%C5%A1ov&hl=cs&ie=UTF8&sll=48.294286,18.074076&sspn=0.005353,0.011362&hnear=Hlavn%C3%A1+2887%2F33,+080+01+Pre%C5%A1ov,+Slovensko&t=m&z=16'),
    (N'Kontakty_Partner5_Region', N'Spolupráce na Slovensku'),
    (N'Kontakty_Partner5_Name', N'Mgr. art. Valerián Tokár'),
    (N'Kontakty_Partner5_Address', N'Smetanova 8, 811 03 Bratislava'),
    (N'Kontakty_Partner5_Country', N'Slovensko'),
    (N'Kontakty_Partner5_Phone', N'+421 903 919 714'),
    (N'Kontakty_Partner5_Email', N'valerian.tokar@gmail.com'),
    (N'Kontakty_Partner5_ICO', N'40252345'),
    (N'Kontakty_Partner5_MapUrl', N'https://maps.google.com/maps?q=Smetanova+8+811+03+Bratislava&hl=cs&sll=48.429465,17.54583&sspn=0.085428,0.181789&hnear=Smetanova+8,+811+03+Bratislava,+Slovensko&t=m&z=16'),
    (N'Kontakty_Partner6_Region', N'Spolupráce na Slovensku'),
    (N'Kontakty_Partner6_Type', N'DISTRIBUTOR pro anglicky mluvící země'),
    (N'Kontakty_Partner6_Name', N'Mgr. Marko Semes, M.B.A.'),
    (N'Kontakty_Partner6_Address', N'P.O. Box 63, 85000 Bratislava 5, Slovensko'),
    (N'Kontakty_Partner6_Phone', N'+421918607818'),
    (N'Kontakty_Partner6_Email', N'semes.marko@gmail.com'),
    (N'Kontakty_Partner6_Skype', N'Marko Semeš'),
    (N'Kontakty_Partner6_MapUrl', N'https://web.archive.org/web/20210516233809im_/http://www.imagodt.cz/kontakt');

INSERT INTO DictionaryEntries (PageId, EntryKey, ContentText)
SELECT 10, t.EntryKey, t.ContentText FROM @texts t
WHERE NOT EXISTS (SELECT 1 FROM DictionaryEntries d WHERE d.PageId = 10 AND d.EntryKey = t.EntryKey);

INSERT INTO EditingDictionaryEntries (PageId, EntryKey, ContentText)
SELECT 10, t.EntryKey, t.ContentText FROM @texts t
WHERE NOT EXISTS (SELECT 1 FROM EditingDictionaryEntries e WHERE e.PageId = 10 AND e.EntryKey = t.EntryKey);
